# YAZI config, blazing fast terminal file manager.
# Maintainer:  Jessee Chan <CYPHER0@foxmail.com>
# Last Change: 2024.10.28


"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
  ratio          = [ 3, 7, 10 ]
  scrolloff      = 5
  linemode       = "size"
  sort_by        = "extension"
  sort_sensitive = false
  sort_reverse 	 = false
  sort_translit  = false
  sort_dir_first = true
  show_symlink   = false
  show_hidden    = false
  mouse_events   = [ "click", "scroll" ]
  title_format   = "Yazi: {cwd}"
  # sort_by        = "alphabetical"

[input]
  cursor_blink  = false

  # cd
  cd_title      = "Change directory:"
  cd_origin     = "top-center"
  cd_offset     = [ 0, 2, 50, 3 ]

  # create
  create_title = ["Create:", "Create (dir):"]
  create_origin = "top-center"
  create_offset = [ 0, 2, 50, 3 ]

  # filter
  filter_title  = "Filter:"
  filter_origin = "top-center"
  filter_offset = [ 0, 2, 50, 3 ]

  # find
  find_title    = [ "Find next:", "Find previous:" ]
  find_origin   = "top-center"
  find_offset   = [ 0, 2, 50, 3 ]

  # search
  search_title  = "Search via {n}:"
  search_origin = "top-center"
  search_offset = [ 0, 2, 50, 3 ]

  # shell
  shell_title   = [ "Shell:", "Shell (block):" ]
  shell_origin  = "top-center"
  shell_offset  = [ 0, 2, 50, 3 ]

  # rename
  rename_title  = "Rename:"
  rename_origin = "hovered"
  rename_offset = [ 0, 1, 50, 3 ]

[pick]
  open_title    = "Open with:"
  open_origin   = "hovered"
  open_offset   = [ 0, 1, 50, 7 ]

[confirm]
  # trash
  trash_title 	    = "Trash {n} selected file{s}?"
  trash_origin	    = "center"
  trash_offset	    = [ 0, 0, 70, 20 ]

  # delete
  delete_title 	    = "Permanently delete {n} selected file{s}?"
  delete_origin	    = "center"
  delete_offset	    = [ 0, 0, 70, 20 ]

  # overwrite
  overwrite_title   = "Overwrite file?"
  overwrite_content = "Will overwrite the following file:"
  overwrite_origin  = "center"
  overwrite_offset  = [ 0, 0, 50, 15 ]

  # quit
  quit_title        = "Quit?"
  quit_content      = "The following task is still running, are you sure you want to quit?"
  quit_origin       = "center"
  quit_offset       = [ 0, 0, 50, 15 ]

[which]
  sort_by      	 = "none"
  sort_sensitive = false
  sort_reverse 	 = false
  sort_translit  = false

[tasks]
  micro_workers    = 10
  macro_workers    = 20
  bizarre_retry    = 5
  image_alloc      = 536870912  # 512MB
  image_bound      = [ 0, 0 ]
  suppress_preload = false

[preview]
  wrap            = "no"
  tab_size        = 2
  max_width       = 600
  max_height      = 900
  cache_dir       = ""
  image_filter    = "triangle"
  image_delay     = 100
  image_quality   = 50
  sixel_fraction  = 20
  ueberzug_scale  = 1
  ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
  editor = [{ run = "nvim       %s", block  = true, for = "unix" },]
  player = [{ run = "mpv        %s", orphan = true, for = "unix" },]
  reader = [{ run = "firefox    %s", orphan = true, for = "unix" },]
  office = [{ run = "onlyoffice-desktopeditors %s", orphan = true, for = "unix" },]

  opener = [{ run = "xdg-open %s", desc = "Opener", for = "linux" },]
	reveal = [{ run = "xdg-open %d", desc = "Reveal", for = "linux" },]

  extract = [
  	{ run = "ya pub extract --list %s",   desc = "Extract here" },
    ]
  download = [
  	{ run = "ya emit download --open %S", desc = "Download and open" },
  	{ run = "ya emit download %S",        desc = "Download" },
    ]

[open]
  rules = [

  # media
	{ mime = "text/*"  , use = [ "editor" , "reveal" ] },
	{ mime = "image/*" , use = [ "player" , "reveal" ] },
	{ mime = "audio/*" , use = [ "player" , "reveal" ] },
	{ mime = "video/*" , use = [ "player" , "reveal" ] },
  { url  = "*.txt"   , use = [ "editor" , "reveal" ]},
  { url  = "*.jpg"   , use = [ "player" , "reveal" ]},
  { url  = "*.mp3"   , use = [ "player" , "reveal" ]},
  { url  = "*.mp4"   , use = [ "player" , "reveal" ]},

  # # office
  { url  = "*.pdf"   , use = [ "reader" , "reveal" ]},
  { url  = "*.doc"   , use = [ "office" , "reveal" ]},
  { url  = "*.docx"  , use = [ "office" , "reveal" ]},
  { url  = "*.xls"   , use = [ "office" , "reveal" ]},
  { url  = "*.xlsx"  , use = [ "office" , "reveal" ]},
  { url  = "*.ppt"   , use = [ "office" , "reveal" ]},
  { url  = "*.pptx"  , use = [ "office" , "reveal" ]},

	# Archive
	{ mime = "application/x-{tar,rar,bzip*,xz}", use = [ "extract", "reveal" ] },
	{ mime = "application/x-{7z-compressed}"   , use = [ "extract", "reveal" ] },
	{ mime = "application/{,g}zip"             , use = [ "extract", "reveal" ] },

	# Virtual file system
	{ mime = "vfs/{absent,stale}", use = ["download"] },
	# Folder
	{ url  = "*/"          , use = [ "opener", "reveal" ] },
	# Empty file
	{ mime = "inode/empty" , use = [ "editor", "reveal" ] },
	# Fallback
	{ url  = "*"           , use = [ "editor", "reader" ] },
  ]

[plugin]

fetchers = [
	# Mimetype
	{ id = "mime", url = "*/",         run = "mime.dir",    prio = "high" },
	{ id = "mime", url = "local://*",  run = "mime.local",  prio = "high" },
	{ id = "mime", url = "remote://*", run = "mime.remote", prio = "high" },
  ]

spotters = [
	{ url = "*/"     , run = "folder" },

  # image
  	{ url = "*.jpg",  run = "mpviewer" },
  	{ url = "*.png",  run = "mpviewer" },
  	{ url = "*.gif",  run = "mpviewer" },
  	{ url = "*.bmp",  run = "mpviewer" },
  	{ url = "*.tif",  run = "mpviewer" },
  	{ url = "*.tiff", run = "mpviewer" },

  # audio
  	{ url = "*.mp3",  run = "mpviewer" },
  	{ url = "*.m4a",  run = "mpviewer" },
  	{ url = "*.aac",  run = "mpviewer" },
  	{ url = "*.ogg",  run = "mpviewer" },
  	{ url = "*.wav",  run = "mpviewer" },
  	{ url = "*.flac", run = "mpviewer" },

  # video
  	{ url = "*.mp4",  run = "mpviewer" },
  	{ url = "*.m4v",  run = "mpviewer" },
  	{ url = "*.mkv",  run = "mpviewer" },
  	{ url = "*.flv",  run = "mpviewer" },
  	{ url = "*.avi",  run = "mpviewer" },
  	{ url = "*.webm", run = "mpviewer" },

  # Text
  	{ mime = "text/*"                           , run = "code"  },
  	{ mime = "*/{xml,javascript}"               , run = "code"  },
  	{ mime = "*/{x-wine-extension-ini}"         , run = "code"  },
  	{ mime = "application/{json,x-ndjson}"      , run = "json"    },

  # Archive
  	{ mime = "application/x-{tar,rar,bzip*,xz}" , run = "archive" },
  	{ mime = "application/x-{7z-compressed}"    , run = "archive" },
  	{ mime = "application/{,g}zip"              , run = "archive" },
  	{ mime = "application/x-{iso9660-image}"    , run = "archive" },

	# Virtual file system
	{ mime = "vfs/*" , run = "vfs" },
	# Error
	{ mime = "null/*", run = "null" },
	# Fallback
	{ url = "*"      , run = "file" },

  ]

previewers = [
  { url  = "*/"                               , run = "folder" },

  # image
  	{ url = "*.jpg",  run = "mpviewer" },
  	{ url = "*.png",  run = "mpviewer" },
  	{ url = "*.gif",  run = "mpviewer" },
  	{ url = "*.bmp",  run = "mpviewer" },
  	{ url = "*.tif",  run = "mpviewer" },
  	{ url = "*.tiff", run = "mpviewer" },

  # audio
  	{ url = "*.mp3",  run = "mpviewer" },
  	{ url = "*.m4a",  run = "mpviewer" },
  	{ url = "*.aac",  run = "mpviewer" },
  	{ url = "*.ogg",  run = "mpviewer" },
  	{ url = "*.wav",  run = "mpviewer" },
  	{ url = "*.flac", run = "mpviewer" },

  # video
  	{ url = "*.mp4",  run = "mpviewer" },
  	{ url = "*.m4v",  run = "mpviewer" },
  	{ url = "*.mkv",  run = "mpviewer" },
  	{ url = "*.flv",  run = "mpviewer" },
  	{ url = "*.avi",  run = "mpviewer" },
  	{ url = "*.webm", run = "mpviewer" },

  # Text
  	{ mime = "text/*"                           , run = "code"  },
  	{ mime = "*/{xml,javascript}"               , run = "code"  },
  	{ mime = "*/{x-wine-extension-ini}"         , run = "code"  },
  	{ mime = "application/{json,x-ndjson}"      , run = "json"    },

  # Archive
  	{ mime = "application/x-{tar,rar,bzip*,xz}" , run = "archive" },
  	{ mime = "application/x-{7z-compressed}"    , run = "archive" },
  	{ mime = "application/{,g}zip"              , run = "archive" },
  	{ mime = "application/x-{iso9660-image}"    , run = "archive" },

	# Font
  	{ mime = "font/*"                           , run = "font"    },
  	{ mime = "application/vnd.ms-opentype"      , run = "font"    },

  # Fallback
  	{ mime = "inode/x-empty"                    , run = "empty"   },
  	{ url  = "*"                                , run = "file"    },

  ]


