# RANGER config,
# Maintainer:  Jessee Chan <CYPHER0@foxmail.com>
# Last Change: 2024.08.22


from os import getenv

class Color:

# pr vd rh | 4 6 8
    gypr=getenv('COLOR_GYPR')
    gyvd=getenv('COLOR_GYVD')
    gyrh=getenv('COLOR_GYRH')
    repr=getenv('COLOR_REPR')
    revd=getenv('COLOR_REVD')
    rerh=getenv('COLOR_RERH')
    orpr=getenv('COLOR_ORPR')
    orvd=getenv('COLOR_ORVD')
    orrh=getenv('COLOR_ORRH')
    yepr=getenv('COLOR_YEPR')
    yevd=getenv('COLOR_YEVD')
    yerh=getenv('COLOR_YERH')
    lepr=getenv('COLOR_LEPR')
    levd=getenv('COLOR_LEVD')
    lerh=getenv('COLOR_LERH')
    grpr=getenv('COLOR_GRPR')
    grvd=getenv('COLOR_GRVD')
    grrh=getenv('COLOR_GRRH')
    sgpr=getenv('COLOR_SGPR')
    sgvd=getenv('COLOR_SGVD')
    sgrh=getenv('COLOR_SGRH')
    cypr=getenv('COLOR_CYPR')
    cyvd=getenv('COLOR_CYVD')
    cyrh=getenv('COLOR_CYRH')
    sbpr=getenv('COLOR_SBPR')
    sbvd=getenv('COLOR_SBVD')
    sbrh=getenv('COLOR_SBRH')
    blpr=getenv('COLOR_BLPR')
    blvd=getenv('COLOR_BLVD')
    blrh=getenv('COLOR_BLRH')
    vipr=getenv('COLOR_VIPR')
    vivd=getenv('COLOR_VIVD')
    virh=getenv('COLOR_VIRH')
    mapr=getenv('COLOR_MAPR')
    mavd=getenv('COLOR_MAVD')
    marh=getenv('COLOR_MARH')
    pipr=getenv('COLOR_PIPR')
    pivd=getenv('COLOR_PIVD')
    pirh=getenv('COLOR_PIRH')

# gy dt sk | 14 12 10
    gygy=getenv('COLOR_GYGY')
    gydt=getenv('COLOR_GYDT')
    gysk=getenv('COLOR_GYSK')
    regy=getenv('COLOR_REGY')
    redt=getenv('COLOR_REDT')
    resk=getenv('COLOR_RESK')
    orgy=getenv('COLOR_ORGY')
    ordt=getenv('COLOR_ORDT')
    orsk=getenv('COLOR_ORSK')
    yegy=getenv('COLOR_YEGY')
    yedt=getenv('COLOR_YEDT')
    yesk=getenv('COLOR_YESK')
    legy=getenv('COLOR_LEGY')
    ledt=getenv('COLOR_LEDT')
    lesk=getenv('COLOR_LESK')
    grgy=getenv('COLOR_GRGY')
    grdt=getenv('COLOR_GRDT')
    grsk=getenv('COLOR_GRSK')
    sggy=getenv('COLOR_SGGY')
    sgdt=getenv('COLOR_SGDT')
    sgsk=getenv('COLOR_SGSK')
    cygy=getenv('COLOR_CYGY')
    cydt=getenv('COLOR_CYDT')
    cysk=getenv('COLOR_CYSK')
    sbgy=getenv('COLOR_SBGY')
    sbdt=getenv('COLOR_SBDT')
    sbsk=getenv('COLOR_SBSK')
    blgy=getenv('COLOR_BLGY')
    bldt=getenv('COLOR_BLDT')
    blsk=getenv('COLOR_BLSK')
    vigy=getenv('COLOR_VIGY')
    vidt=getenv('COLOR_VIDT')
    visk=getenv('COLOR_VISK')
    magy=getenv('COLOR_MAGY')
    madt=getenv('COLOR_MADT')
    mask=getenv('COLOR_MASK')
    pigy=getenv('COLOR_PIGY')
    pidt=getenv('COLOR_PIDT')
    pisk=getenv('COLOR_PISK')

# bk dk dp | 30 26 22
    gybk=getenv('COLOR_GYBK')
    gydk=getenv('COLOR_GYDK')
    gydp=getenv('COLOR_GYDP')
    rebk=getenv('COLOR_REBK')
    redk=getenv('COLOR_REDK')
    redp=getenv('COLOR_REDP')
    orbk=getenv('COLOR_ORBK')
    ordk=getenv('COLOR_ORDK')
    ordp=getenv('COLOR_ORDP')
    yebk=getenv('COLOR_YEBK')
    yedk=getenv('COLOR_YEDK')
    yedp=getenv('COLOR_YEDP')
    lebk=getenv('COLOR_LEBK')
    ledk=getenv('COLOR_LEDK')
    ledp=getenv('COLOR_LEDP')
    grbk=getenv('COLOR_GRBK')
    grdk=getenv('COLOR_GRDK')
    grdp=getenv('COLOR_GRDP')
    sgbk=getenv('COLOR_SGBK')
    sgdk=getenv('COLOR_SGDK')
    sgdp=getenv('COLOR_SGDP')
    cybk=getenv('COLOR_CYBK')
    cydk=getenv('COLOR_CYDK')
    cydp=getenv('COLOR_CYDP')
    sbbk=getenv('COLOR_SBBK')
    sbdk=getenv('COLOR_SBDK')
    sbdp=getenv('COLOR_SBDP')
    blbk=getenv('COLOR_BLBK')
    bldk=getenv('COLOR_BLDK')
    bldp=getenv('COLOR_BLDP')
    vibk=getenv('COLOR_VIBK')
    vidk=getenv('COLOR_VIDK')
    vidp=getenv('COLOR_VIDP')
    mabk=getenv('COLOR_MABK')
    madk=getenv('COLOR_MADK')
    madp=getenv('COLOR_MADP')
    pibk=getenv('COLOR_PIBK')
    pidk=getenv('COLOR_PIDK')
    pidp=getenv('COLOR_PIDP')

# wt lt sl | 46 42 38
    gywt=getenv('COLOR_GYWT')
    gylt=getenv('COLOR_GYLT')
    gysl=getenv('COLOR_GYSL')
    rewt=getenv('COLOR_REWT')
    relt=getenv('COLOR_RELT')
    resl=getenv('COLOR_RESL')
    orwt=getenv('COLOR_ORWT')
    orlt=getenv('COLOR_ORLT')
    orsl=getenv('COLOR_ORSL')
    yewt=getenv('COLOR_YEWT')
    yelt=getenv('COLOR_YELT')
    yesl=getenv('COLOR_YESL')
    lewt=getenv('COLOR_LEWT')
    lelt=getenv('COLOR_LELT')
    lesl=getenv('COLOR_LESL')
    grwt=getenv('COLOR_GRWT')
    grlt=getenv('COLOR_GRLT')
    grsl=getenv('COLOR_GRSL')
    sgwt=getenv('COLOR_SGWT')
    sglt=getenv('COLOR_SGLT')
    sgsl=getenv('COLOR_SGSL')
    cywt=getenv('COLOR_CYWT')
    cylt=getenv('COLOR_CYLT')
    cysl=getenv('COLOR_CYSL')
    sbwt=getenv('COLOR_SBWT')
    sblt=getenv('COLOR_SBLT')
    sbsl=getenv('COLOR_SBSL')
    blwt=getenv('COLOR_BLWT')
    bllt=getenv('COLOR_BLLT')
    blsl=getenv('COLOR_BLSL')
    viwt=getenv('COLOR_VIWT')
    vilt=getenv('COLOR_VILT')
    visl=getenv('COLOR_VISL')
    mawt=getenv('COLOR_MAWT')
    malt=getenv('COLOR_MALT')
    masl=getenv('COLOR_MASL')
    piwt=getenv('COLOR_PIWT')
    pilt=getenv('COLOR_PILT')
    pisl=getenv('COLOR_PISL')

# bg fg | 60 68 -1
    rebg=getenv('COLOR_REBG')
    refg=getenv('COLOR_REFG')
    orbg=getenv('COLOR_ORBG')
    orfg=getenv('COLOR_ORFG')
    yebg=getenv('COLOR_YEBG')
    yefg=getenv('COLOR_YEFG')
    lebg=getenv('COLOR_LEBG')
    lefg=getenv('COLOR_LEFG')
    grbg=getenv('COLOR_GRBG')
    grfg=getenv('COLOR_GRFG')
    sgbg=getenv('COLOR_SGBG')
    sgfg=getenv('COLOR_SGFG')
    cybg=getenv('COLOR_CYBG')
    cyfg=getenv('COLOR_CYFG')
    sbbg=getenv('COLOR_SBBG')
    sbfg=getenv('COLOR_SBFG')
    blbg=getenv('COLOR_BLBG')
    blfg=getenv('COLOR_BLFG')
    vibg=getenv('COLOR_VIBG')
    vifg=getenv('COLOR_VIFG')
    mabg=getenv('COLOR_MABG')
    mafg=getenv('COLOR_MAFG')
    pibg=getenv('COLOR_PIBG')
    pifg=getenv('COLOR_PIFG')


