# SWAYBAR config,
# Maintainer:	 Jessee Chan <CYPHER0@foxmail.com>
# Last Change: 2024.11.05


icons_format          = "{icon}"
  [icons]
  icons               = "default"
  [theme]
  theme               = "darkgrey"

[overrides]
  idle_fg      = "#d0d0d0"
  info_fg      = "#a0a0ff"
  good_fg      = "#a0ffa0"
  warning_fg   = "#ffffa0"
  critical_fg  = "#ffa0a0"

[[block]]
  block               = "custom"
  command             = "~/.config/swaybar/block/netflow.dsh"
  persistent          = true

[[block]]
  block               = "cpu"
  interval            = 1
  format              = "$icon $utilization"
  format_alt          = "$icon $utilization[$frequency]{$boost|}$barchart"
  warning_cpu         = 60
  critical_cpu        = 80
  info_cpu            = 20
[block.theme_overrides]
  idle_fg = "#d0ffa0"

[[block]]
  block               = "memory"
  format              = "$icon $mem_used_percents.eng(w:1)"
  format_alt          = "$icon $mem_used_percents.eng(w:1)[$mem_used.eng(w:3,u:B,p:Mi)/$mem_total.eng(w:3,u:B,p:Mi)]"
  # format_alt          = "$icon $swap_used_percents.eng(w:2)[$swap_used.eng(w:3,u:B,p:Mi)/$swap_total.eng(w:3,u:B,p:Mi)]"
  interval            = 1
  warning_mem         = 60
  critical_mem        = 80
[block.theme_overrides]
  idle_fg = "#d0ffa0"

[[block]]
  block               = "disk_space"
  format              = "$icon $available"
  format_alt          = "$icon $percentage[$available/$total]"
  interval            = 360
  warning             = 20.0
  alert               = 10.0
  path                = "/"
  info_type           = "available"
  alert_unit          = "GB"
  [[block.click]]
  button              = "right"
  update              = true
[block.theme_overrides]
  idle_fg = "#d0d0d0"

[[block]]
  block               = "bluetooth"
  mac                 = "00:18:09:92:1B:BA"
  format              = "{$icon} "
  # format_alt          ="{$icon} [$name][$available]"
  disconnected_format = "{$icon}x"
[block.theme_overrides]
  idle_fg = "#a0d0ff"

[[block]]
  block               = "net"
  format              = "{$icon} "
  format_alt          = "{$icon} [$ssid]$signal_strength"
  inactive_format     = "{$icon}x"
[block.theme_overrides]
  idle_fg = "#a0ffd0"

[[block]]
  block               = "sound"
  format              = "$icon $volume"
[block.theme_overrides]
  idle_fg = "#d0d0d0"

[[block]]
  block               = "time"
  format              = "$timestamp.datetime(f:'%d/%b %T %a') "
  interval            = 1
[block.theme_overrides]
  idle_fg = "#ffd0a0"

[[block]]
  block               = "custom"
  command             = "echo  "
[block.theme_overrides]
  idle_fg = "#5080b0"


