# ALACRITTY config, color


[colors]
  transparent_background_colors = true
  cursor         = { text = "CellBackground", cursor = "CellForeground" }
  vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }
  primary        = { foreground = "#d0d0d0",  background = "#303030"  }

[colors.normal]
  red      = "#b08050"
  green    = "#50b080"
  blue     = "#5080b0"
  yellow   = "#b0b050"
  cyan     = "#50b0b0"
  magenta  = "#b050b0"

[colors.bright]
  red      = "#ffd0a0"
  green    = "#a0ffd0"
  blue     = "#a0d0ff"
  yellow   = "#ffffa0"
  cyan     = "#a0ffff"
  magenta  = "#ffa0ff"

[colors.dim]
  red      = "#b05050"
  green    = "#50b050"
  blue     = "#5050b0"
  yellow   = "#80b050"
  cyan     = "#8050b0"
  magenta  = "#b05080"


