# ALACRITTY config,


[keyboard]
bindings = [

# General Mode
  {key= "Copy",                   action= "Copy"  },
  {key= "Paste",                  action= "Paste" },

# (Windows,Linux, only)
  {key= "V",     mods= "Control", action= "Paste" },

]


