# LEMURS config, a tui login manager.
# Maintainer:  Jessee Chan <CYPHER0@foxmail.com>
# Last Change: 2024.11.05


# General

  tty                   = 2
  x11_display           = ":0"
  xserver_timeout_secs  = 10
  pam_service           = "lemurs"
  shell_login_flag      = "short"
  focus_behaviour       = "default"

  do_log                = true
  main_log_path         = "/var/log/lemurs.log"
  xserver_log_path      = "/var/log/lemurs.xorg.log"
  client_log_path       = "/var/log/lemurs.client.log"

  # [x11]
  # scripts_path          = "/etc/lemurs/xorg"
  # xsessions_path        = "/usr/share/xsessions"

  # [wayland]
  # scripts_path          = "/etc/lemurs/wayland"
  # wayland_sessions_path = "/usr/share/wayland-sessions"

[background]

  show_background              = true
  [background.style]
  show_border                  = true

  color                        = "$screen_bg"
  border_color                 = "$border_fg"

[power_controls]

  allow_shutdown               = true
  allow_reboot                 = true
  hint_margin                  = 2

  reboot_key                   = "F11"
  shutdown_key                 = "F12"
  reboot_cmd                   = "systemctl reboot   -l"
  shutdown_cmd                 = "systemctl poweroff -l"

  reboot_hint                  = "Reboot %key%"
  shutdown_hint                = "Shutdown %key%"
  shutdown_hint_modifiers      = ""
  reboot_hint_modifiers        = ""

  reboot_hint_color            = "$reboot_hint_fg"
  shutdown_hint_color          = "$shutdown_hint_fg"

[environment_switcher]

  switcher_visibility          = "visible"
  include_tty_shell            = true
  remember                     = true
  max_display_length           = 8

  toggle_hint                  = "Switcher %key%"
  toggle_hint_modifiers        = ""

  show_movers                  = true
  mover_margin                 = 1
  left_mover                   = "<"
  right_mover                  = ">"
  mover_modifiers              = ""
  mover_modifiers_focused      = "bold"

  show_neighbours              = true
  neighbour_margin             = 1
  neighbour_modifiers          = ""
  neighbour_modifiers_focused  = ""

  selected_modifiers           = "bold"
  selected_modifiers_focused   = "underlined"

  no_envs_text                 = "NO ENV ..."
  no_envs_modifiers            = ""
  no_envs_modifiers_focused    = "bold"

  toggle_hint_color            = "$env_toggle_fg"
  mover_color                  = "$env_swaper_fg"
  selected_color               = "$env_select_fg"
  neighbour_color              = "$env_beside_fg"
  no_envs_color                = "$env_noenvs_fg"
  mover_color_focused          = "$env_swaper_fg_focus"
  selected_color_focused       = "$env_select_fg_focus"
  neighbour_color_focused      = "$env_beside_fg_focus"
  no_envs_color_focused        = "$env_noenvs_fg_focus"

[username_field]

  remember                     = true
  [username_field.style]
  show_title                   = true
  show_border                  = true
  use_max_width                = true
  max_width                    = 48
  title                        = "Login"

  title_color                  = "$usr_title_fg"
  content_color                = "$usr_content_fg"
  border_color                 = "$usr_border_fg"
  title_color_focused          = "$usr_title_fg_focus"
  content_color_focused        = "$usr_content_fg_focus"
  border_color_focused         = "$usr_border_fg_focus"

[password_field]

  content_replacement_character= "*"
  [password_field.style]
  show_title                   = true
  show_border                  = true
  use_max_width                = true
  max_width                    = 48
  title                        = "Password"

  title_color                  = "$pwd_title_fg"
  content_color                = "$pwd_content_fg"
  border_color                 = "$pwd_border_fg"
  title_color_focused          = "$pwd_title_fg_focus"
  content_color_focused        = "$pwd_content_fg_focus"
  border_color_focused         = "$pwd_border_fg_focus"


